### PR TITLE
port to topkg, cleanup bitrot

### LINKED ISSUE #18: mirage-net is now called tcpip - update depopt
The the [opam file](https://github.com/mirage/ocaml-pcap/blob/master/opam#L29) `mirage-net` is marked as a depopt but I think it's now called `tcpip`. Perhaps update this?

### PR DESCRIPTION
**Pull request by hannesm**
fixes #18 and #22 (by removing code)

### CODE REVIEW

**Comment by hannesm** [comment]
I've no clue why appveyor fails to build -- travis is happy

**Comment by yomimono** [comment]
Previous appveyor problem fixed, exciting new appveyor problem looks like the one discovered in https://github.com/ocaml/ocaml-ci-scripts/pull/150 .

**Comment by hannesm** [comment]
since https://github.com/ocaml/opam-repository/pull/8386 is merged, getting a new pcap-format release is crucial for MirageOS3.  I'd really like to hear what people think about the `mirage` and `print` subfolders, and especially if someone uses that code or wants to maintain it and keep it.

**Comment by yomimono** [comment]
Most of my code that uses this library was written for `0.3` and hasn't been updated even for `0.4`, so my opinion shouldn't count for much.  `mirage-tcpip`'s tests are the heaviest current user of `pcap` that I know of, and they use only the `Pcap` module.  I wouldn't mind if `mirage` and `print` went away.

@djs55 and @magnuss may also have opinions here.

**Comment by mor1** [comment]
All looks good to me.
I'm happy to merge this tomorrow unless @djs55 or @MagnusS speaks up firmly against doing so before then.

**Comment by mor1** [comment]
Silence is taken for consent. (We can always add things back in if it turns out removing them was bad.) Merging...

**Comment by hannesm** [comment]
@mor1 thanks!  could you also do a release of pcap-format to opam-repository (see roughly https://github.com/mirage/mirageos-3-beta/issues/1#issuecomment-272895274 for how to), so that in mirage3 we can have a conflict-free pcap-format package?

**Comment by mor1** [comment]
@hannesm I believe I just did a release -- could you try it out and see whether I did it right? (My first release with `topkg` :)

**Comment by hannesm** [comment]
yes, looks good! even properly watermarked :+1: 

now do a `topkg opam pkg` and submit that to opam-repository :) (or use `topkg opam submit` if you've opam publish installed)

**Comment by mor1** [comment]
Done! I await CI outcomes...

**Pull request merged**
